apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
spec:
  selector:
    matchLabels:
      run: demo-nginx
  replicas: 4
  template:
    metadata:
      labels:
        run: demo-nginx
    spec:
      containers:
      - name: demo-nginx
        image: nginx
        ports:
        - containerPort: 80
